import type { TheGlobalistContract } from './schema';

const slides: TheGlobalistContract = {
  slides: [
    {
      id: 'tg-cover-1', type: 'cover',
      tag: 'SPECIAL REPORT',
      headline: 'The End of Cheap Capital.',
      subheadline: 'How the sudden shift to high-interest regimes is forcing legacy conglomerates to restructure, liquidate, or perish entirely.',
      authorName: 'Julian Sterling',
      authorRole: 'Reporting from Frankfurt',
      footerLeft: 'MACRO-ECONOMICS', footerRight: 'PAGE 01',
    },
    {
      id: 'tg-seq-1', type: 'sequence',
      tag: 'THE BRIEFING',
      headline: 'The Executive Briefing',
      items: [
        { num: '1', title: 'Zombie Companies Collapse', desc: 'Enterprises kept alive purely by refinancing debt at near-zero rates are facing immediate insolvency as terms rigidly reset.' },
        { num: '2', title: 'M&A Activity Freezes', desc: 'Without cheap leverage, mega-mergers have completely stalled. Private equity is pivoting strictly toward operational turnarounds.' },
        { num: '3', title: 'The Profitability Mandate', desc: 'Venture capital has abandoned the "growth at all costs" mantra. Startups are now graded strictly on cash flow and runway.' },
      ],
      footerLeft: 'THE BRIEFING', footerRight: 'PAGE 02',
    },
    {
      id: 'tg-img-1', type: 'image-split',
      tag: 'DISPATCH',
      headline: 'The ECB Holds Firm',
      bodyText: 'Despite immense pressure from southern European economies, the central bank refuses to blink. Inflation targets remain the singular, uncompromising mandate, even if it triggers a mild continental recession.',
      imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1080&auto=format&fit=crop',
      credit: 'Fig. 01 — Frankfurt',
      footerLeft: 'DISPATCH', footerRight: 'PAGE 03',
    },
    {
      id: 'tg-telem-1', type: 'telemetry',
      tag: 'Q3 DATA SET',
      headline: 'Global Telemetry',
      stats: [
        { value: '5.25', unit: '%', label: 'Current baseline interest rate, marking a 22-year high for western markets.' },
        { value: '1.4', unit: 'T', label: 'Estimated volume of corporate debt maturing globally within the next 18 months.' },
        { value: '-18', unit: '%', label: 'Decline in commercial real estate valuations in major metropolitan financial hubs.' },
        { value: '600', unit: 'k', label: 'White-collar tech and finance roles eliminated globally since the tightening cycle began.' },
      ],
      footerLeft: 'TELEMETRY', footerRight: 'PAGE 04',
    },
    {
      id: 'tg-interview-1', type: 'interview',
      tag: 'INTERVIEW',
      headline: 'The Interview',
      question: 'Is the era of hyper-growth permanently dead, or is this merely a cyclical pause before rates drop?',
      answer: 'It is structurally dead. The last ten years were a historical anomaly fueled by massive quantitative easing. We are returning to historical norms where capital actually costs money. Companies must now prove they can generate a profit today, not in 2030.',
      respondentName: 'Dr. Elena Rostova',
      respondentRole: 'Chief Economist',
      footerLeft: 'INTERVIEW', footerRight: 'PAGE 05',
    },
    {
      id: 'tg-quad-1', type: 'quadrant',
      tag: 'STRATEGY',
      headline: 'Strategic Positioning',
      topLeft: { title: 'The Vulnerable', desc: 'Commodity services charging a premium. First to be cut in a recession.' },
      topRight: { title: 'The Monopolist', desc: 'Irreplaceable IP combined with supreme pricing power. The ideal state.' },
      bottomLeft: { title: 'The Grinder', desc: 'Competing purely on volume and price. A stressful race to the bottom.' },
      bottomRight: { title: 'The Utility', desc: 'Necessary infrastructure but unable to extract premium profits from clients.' },
      topLabel: 'High Margin',
      bottomLabel: 'Low Margin',
      leftLabel: 'Low Moat',
      rightLabel: 'High Moat',
      highlight: 'topRight',
      footerLeft: 'STRATEGY', footerRight: 'PAGE 06',
    },
    {
      id: 'tg-cs-1', type: 'case-study',
      tag: 'CASE STUDY',
      headline: "TechCorp's Pivot",
      stages: [
        { label: 'Context', title: 'Bloated Infrastructure', desc: 'In 2024, headcount had expanded 40% while core revenue remained flat. Engineering velocity had entirely stalled.' },
        { label: 'Action', title: 'The Flattening', desc: 'Eliminated middle management entirely. Shifted to small, autonomous teams and aggressively cut non-core product lines.' },
        { label: 'Result', title: 'Margin Expansion', desc: 'Net profit margin surged from 12% to 28%. Shipping speed doubled, resulting in an immediate stock re-rating.', highlighted: true },
      ],
      footerLeft: 'CASE STUDY', footerRight: 'PAGE 07',
    },
    {
      id: 'tg-myth-1', type: 'myth-fact',
      tag: 'ANALYSIS',
      headline: 'Correcting the Record',
      myth: 'Companies must always choose between aggressive growth and sustainable profitability.',
      fact: 'True operational leverage allows for compounding growth while expanding margins. Efficiency is a catalyst.',
      footerLeft: 'ANALYSIS', footerRight: 'PAGE 08',
    },
    {
      id: 'tg-res-1', type: 'resource-grid',
      tag: 'TOOLKIT',
      headline: "The Strategist's Toolkit",
      items: [
        { title: 'Bloomberg Terminal', desc: 'The undisputed heavyweight for real-time macroeconomic data, news, and complex financial instruments.' },
        { title: 'Capital IQ', desc: 'Essential for deep fundamental analysis, M&A tracking, and untangling complex global corporate structures.' },
        { title: 'The Economist', desc: 'Weekly synthesis of global affairs providing the critical qualitative context required beyond the raw data.' },
        { title: 'Stratfor', desc: 'Geopolitical intelligence platform used by executives to anticipate regulatory and major supply chain shifts.' },
      ],
      footerLeft: 'TOOLKIT', footerRight: 'PAGE 09',
    },
    {
      id: 'tg-tl-1', type: 'timeline',
      tag: 'CHRONOLOGY',
      headline: 'Historical Precedent',
      events: [
        { date: '1970s', title: 'The Inflation Shock', desc: 'Oil embargoes trigger stagflation, forcing central banks into aggressive, painful monetary tightening.' },
        { date: '1981', title: 'The Volcker Shock', desc: 'Interest rates pushed to 20% to break the back of inflation, inducing a severe but historically necessary recession.' },
        { date: '2026', title: 'The Modern Echo', desc: 'Policy makers study the 70s, attempting to tightly engineer a soft landing while maintaining restrictive rates.', highlight: true },
      ],
      footerLeft: 'CHRONOLOGY', footerRight: 'PAGE 10',
    },
    {
      id: 'tg-quote-1', type: 'quote',
      tag: 'PERSPECTIVE',
      quote: 'In a low-rate environment, anyone can look like a genius. High rates reveal who actually has a sustainable business model.',
      author: 'Warren Buffett',
      role: 'Chairman, Berkshire Hathaway',
      footerLeft: 'PERSPECTIVE', footerRight: 'PAGE 11',
    },
    {
      id: 'tg-cta-1', type: 'cta',
      tag: 'INTELLIGENCE',
      headline: 'Master the Global Economy.',
      subtext: 'Macro-economic analysis delivered to executives weekly.',
      actionLabel: 'Subscribe Now',
      socialHandle: 'Read more at TheGlobalist.com',
      footerLeft: 'SUBSCRIPTION', footerRight: 'PAGE 12',
    },
  ],
};

export default slides;
