import type { TheCuratorContract } from './schema';

const slides: TheCuratorContract = {
  slides: [
    {
      id: 'tc-cover-1', type: 'cover',
      tag: 'EXHIBITION 01',
      headline: 'The Space Between.',
      subheadline: 'An architectural study of negative space, invisible constraints, and the immense power of omitting the unnecessary.',
      pullQuote: 'True luxury is never loud. It is the quiet confidence of knowing exactly what to leave out.',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 01',
    },
    {
      id: 'tc-seq-1', type: 'sequence',
      tag: 'THE CATALOG',
      headline: 'The Principles.',
      items: [
        { num: 'I.', title: 'Omission as Design', desc: 'The removal of non-essential elements until only the structural truth of the object remains.' },
        { num: 'II.', title: 'Material Integrity', desc: 'Refusing to disguise the underlying materials. Concrete must look like concrete; wood must breathe.' },
        { num: 'III.', title: 'Asymmetric Balance', desc: 'Creating visual tension by placing heavy elements off-center, balanced entirely by vast negative space.' },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 02',
    },
    {
      id: 'tc-img-1', type: 'image-split',
      tag: 'THE GALLERY',
      headline: 'Form & Function.',
      bodyText: 'The Bauhaus movement taught us that utility should dictate shape. When applied to digital strategy, this means stripping away decorative marketing and presenting the user with absolute, unvarnished value.',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1080&auto=format&fit=crop',
      credit: 'FIG. 01 — ARCHITECTURE',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 03',
    },
    {
      id: 'tc-telem-1', type: 'telemetry',
      tag: 'METRICS',
      headline: 'The Metrics.',
      stats: [
        { value: '68', unit: '%', label: 'Cognitive Load Reduction', note: 'When decorative elements are removed from user interfaces.' },
        { value: '3.2', unit: 'x', label: 'Premium Price Multiplier', note: 'The aesthetic-usability effect applied to luxury commodities.' },
        { value: '-45', unit: '%', label: 'Decision Fatigue', note: 'Limiting choices paradoxically increases conversion rates.' },
        { value: '90', unit: '%', label: 'Information Retention', note: 'Achieved through high-contrast, macro-typography pacing.' },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 04',
    },
    {
      id: 'tc-interview-1', type: 'interview',
      tag: 'DIALOGUE',
      headline: 'The Dialogue.',
      question: 'Does minimalism risk alienating consumers who equate complexity with value?',
      answer: 'Only in commodity markets. In the luxury sector, complexity is viewed as an apology for a lack of substance. When you sell at the highest tier, you are selling confidence. Empty space is the ultimate projection of confidence.',
      respondentName: 'Dieter Rams', respondentRole: 'Architect',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 05',
    },
    {
      id: 'tc-quad-1', type: 'quadrant',
      tag: 'TOPOLOGY',
      headline: 'Design Topology.',
      topLeft: { label: 'MAXIMALIST / FUNCTIONAL', title: 'The Dashboard', desc: 'High data density for expert users. E.g., Financial terminals, airplane cockpits.' },
      topRight: { label: 'MAXIMALIST / ORNAMENTAL', title: 'The Baroque', desc: 'Decoration for the sake of status. E.g., Versailles, fast-fashion websites.' },
      bottomLeft: { label: 'MINIMALIST / ORNAMENTAL', title: 'The Brutalist', desc: 'Raw materials exposed. Usability sacrificed for artistic tension.' },
      bottomRight: { label: 'MINIMALIST / FUNCTIONAL', title: 'The Curator', desc: 'Premium positioning. High friction. Asymmetric tension and massive ROI.', highlighted: true },
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 06',
    },
    {
      id: 'tc-cs-1', type: 'case-study',
      tag: 'PROVENANCE',
      headline: 'Provenance.',
      stages: [
        { label: 'CONTEXT', title: 'The Cluttered Gallery', desc: 'A heritage brand struggling with brand dilution due to excessive product lines and loud marketing.' },
        { label: 'ACTION', title: 'The Purge', desc: 'Eliminated 80% of SKUs. Removed all logos from exterior packaging. Tripled the price.' },
        { label: 'RESULT', title: 'Scarcity Premium', desc: 'Revenue dropped 10%, but net profit expanded by 400%. The brand became a status symbol.', highlighted: true },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 07',
    },
    {
      id: 'tc-myth-1', type: 'myth-fact',
      tag: 'ACTUALITY',
      headline: 'Optical Illusions.',
      myth: 'Adding more features justifies a higher price point.',
      fact: 'Removing the unnecessary creates the void required for luxury pricing.',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 08',
    },
    {
      id: 'tc-res-1', type: 'resource-grid',
      tag: 'COLLECTION',
      headline: 'The Collection.',
      items: [
        { num: '01', title: 'Typography', desc: 'Cormorant Garamond. An elegant, razor-thin serif that demands high-resolution displays.' },
        { num: '02', title: 'Negative Space', desc: 'The most expensive asset in design. Treat empty pixels as physical marble.' },
        { num: '03', title: 'Palette', desc: 'Absolute monochrome. Color is only used when structurally necessary for comprehension.' },
        { num: '04', title: 'Restraint', desc: 'The discipline to stop designing when the core message is achieved.' },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 09',
    },
    {
      id: 'tc-tl-1', type: 'timeline',
      tag: 'EVOLUTION',
      headline: 'Evolution of Form.',
      events: [
        { date: 'PHASE I', title: 'The Bauhaus', desc: 'Form follows function. The stripping of ornamentation in favor of industrial utility.' },
        { date: 'PHASE II', title: 'Swiss Style', desc: 'The introduction of the strict mathematical grid and objective photography.' },
        { date: 'PHASE III', title: 'Neo-Minimalism', desc: 'Digital luxury. Vast negative space used specifically to elevate perceived value.', highlight: true },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 10',
    },
    {
      id: 'tc-quote-1', type: 'quote',
      tag: 'STATEMENT',
      quote: 'Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.',
      author: 'Antoine de St. Exupéry',
      role: 'Aviator & Writer',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 11',
    },
    {
      id: 'tc-cta-1', type: 'cta',
      tag: 'ACQUISITION',
      headline: 'Enter the Gallery.',
      subtext: 'A private collection of architectural strategy, delivered to your inbox.',
      actionLabel: 'Acquire Access',
      socialHandle: 'EXHIBITION: @CURATOR.STUDIO',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 12',
    },
    {
      id: 'tc-hero-1', type: 'hero-metric',
      tag: 'HERO METRIC',
      value: '99', unit: '%',
      headline: 'The Signal to Noise Ratio',
      bodyText: 'Most modern communication is entirely disposable. True luxury is found in the one percent of information that actually shifts perspective.',
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 13',
    },
    {
      id: 'tc-method-1', type: 'methodology',
      tag: 'METHODOLOGY',
      headline: 'The Methodology.',
      steps: [
        { num: '01', title: 'Isolation', desc: 'Remove the subject from all contextual noise and decorative elements.' },
        { num: '02', title: 'Proportion', desc: 'Scale the essential elements to absolute maximum visibility. Create tension.' },
        { num: '03', title: 'Execution', desc: 'Publish with uncompromising discipline. Reject client requests for "pop."', highlighted: true },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 14',
    },
    {
      id: 'tc-juxta-1', type: 'juxtaposition',
      tag: 'AESTHETICS',
      headline: 'Aesthetic Code.',
      donts: ['Drop shadows and gradients.', 'Centering all text alignment.', 'Filling every pixel of space.'],
      dos: ['Absolute stark contrast.', 'Asymmetrical tension.', 'Aggressive negative space.'],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 15',
    },
    {
      id: 'tc-check-1', type: 'checklist',
      tag: 'INVENTORY',
      headline: 'The Inventory.',
      items: [
        { text: 'Is the typographic hierarchy immediately obvious?', checked: true },
        { text: 'Have all decorative or non-functional elements been removed?' },
        { text: 'Does the negative space actively support the central object?' },
        { text: 'Is the contrast ratio sufficient for immediate legibility?' },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 16',
    },
    {
      id: 'tc-break-1', type: 'breakdown',
      tag: 'ANATOMY',
      headline: 'Anatomy of Form.',
      centerLabel: 'The Object',
      items: [
        { num: '01', title: 'Structure', desc: 'The underlying grid that governs all spatial decisions.' },
        { num: '02', title: 'Negative Space', desc: 'The intentional void that gives the object permission to breathe.' },
        { num: '03', title: 'Typography', desc: 'The voice of the object, delivered with extreme contrast.' },
        { num: '04', title: 'Material', desc: 'The unvarnished truth of the medium, exposed and honest.' },
      ],
      footerLeft: 'ARCHIVE REF: CURATOR.STUDIO', footerRight: 'PAGE 17',
    },
  ],
};

export default slides;
