import { z } from 'zod';

// Job Status enum (matches PostgreSQL job_status enum)
export const JobStatusEnum = z.enum([
  'queued',
  'ingesting',
  'transcribing',
  'structuring',
  'rendering',
  'complete',
  'failed',
]);
export type JobStatus = z.infer<typeof JobStatusEnum>;

// Source Type enum (matches PostgreSQL source_type enum)
export const SourceTypeEnum = z.enum(['youtube', 'blog', 'article']);
export type SourceType = z.infer<typeof SourceTypeEnum>;

// Format Type enum (matches PostgreSQL format_type enum)
export const FormatTypeEnum = z.enum([
  'carousel_slide',
  'linkedin_post',
  'twitter_thread',
  'instagram_feed',
  'instagram_stories',
  'linkedin_carousel',
  'facebook_carousel',
]);
export type FormatType = z.infer<typeof FormatTypeEnum>;

// Platform enum
export const PlatformEnum = z.enum([
  'instagram-feed',
  'instagram-stories',
  'linkedin',
  'facebook',
]);
export type Platform = z.infer<typeof PlatformEnum>;

// Brand Kit Schema (user input)
export const BrandKitInputSchema = z.object({
  name: z.string().min(1).max(100),
  primaryColor: z.string().regex(/^#([0-9A-F]{3}){1,2}$/i),
  secondaryColor: z.string().regex(/^#([0-9A-F]{3}){1,2}$/i).optional(),
  fontPreference: z.enum(['modern-sans', 'elegant-serif', 'bold-display', 'clean-minimal']).default('modern-sans'),
});
export type BrandKitInput = z.infer<typeof BrandKitInputSchema>;

// Brand Kit Schema (generated by LLM)
export const BrandKitSchema = z.object({
  name: z.string(),
  colors: z.object({
    primary: z.string(),
    secondary: z.string(),
    accent: z.string(),
    background: z.string(),
    surface: z.string(),
    text: z.string(),
    muted: z.string(),
  }),
  fonts: z.object({
    heading: z.string(),
    body: z.string(),
    headingWeight: z.number().min(400).max(900),
    bodyWeight: z.number().min(400).max(900),
  }),
  styleDirection: z.enum(['modern', 'minimal', 'elegant', 'bold', 'organic']),
});
export type BrandKit = z.infer<typeof BrandKitSchema>;

// Color Scheme Schema
export const ColorSchemeSchema = z.object({
  primary: z.string(),
  secondary: z.string(),
  accent: z.string(),
  background: z.string(),
  text: z.string(),
});
export type ColorScheme = z.infer<typeof ColorSchemeSchema>;

// Slide Design Schema
export const SlideDesignSchema = z.object({
  index: z.number(),
  layout: z.string(),
  backgroundType: z.enum(['solid', 'gradient', 'pattern', 'image']),
  gradientType: z.string().optional(),
  gradientColors: z.array(z.string()).optional(),
  imageSearch: z.string().optional(),
  imageBlur: z.number().min(0).max(1).optional(),
  imageOverlay: z.string().optional(),
  textAlignment: z.enum(['left', 'center', 'right']),
  emphasis: z.enum(['small', 'medium', 'large']),
  shapes: z.array(z.object({
    type: z.string(),
    position: z.string(),
    color: z.string().optional(),
    opacity: z.number().min(0).max(1).optional(),
  })),
});
export type SlideDesign = z.infer<typeof SlideDesignSchema>;

// Design Output Schema (LLM output from Call 3)
export const DesignOutputSchema = z.object({
  template: z.string(),
  colorScheme: ColorSchemeSchema,
  slides: z.array(SlideDesignSchema).min(1).max(12),
});
export type DesignOutput = z.infer<typeof DesignOutputSchema>;

// Job Creation Schema (API)
export const JobCreateSchema = z.object({
  sourceUrl: z.string().url(),
  priority: z.union([z.literal(1), z.literal(5), z.literal(10)]).default(5),
  platform: PlatformEnum.default('instagram-feed'),
  brandKit: BrandKitInputSchema.partial().optional(),
  templateId: z.string().optional(),
});
export type JobCreateInput = z.infer<typeof JobCreateSchema>;

// Structured Content Schema (LLM Output - Call 1)
export const SlideContentSchema = z.object({
  heading: z.string().max(100),
  body: z.string().max(500),
  bulletPoints: z.array(z.string().max(100)).max(5).optional(),
});
export type SlideContent = z.infer<typeof SlideContentSchema>;

export const StructuredContentSchema = z.object({
  hook: z.object({
    title: z.string().max(100),
    subtitle: z.string().max(200).optional(),
  }),
  valuePoints: z.array(SlideContentSchema).min(1).max(10),
  callToAction: z.object({
    message: z.string().max(150),
    url: z.string().optional(),
  }),
});
export type StructuredContent = z.infer<typeof StructuredContentSchema>;

// Outbox Event Payload Schemas
export const IngestPayloadSchema = z.object({
  jobId: z.string().uuid(),
  sourceUrl: z.string().url(),
  sourceType: SourceTypeEnum,
});
export type IngestPayload = z.infer<typeof IngestPayloadSchema>;

export const TranscribePayloadSchema = z.object({
  jobId: z.string().uuid(),
  audioR2Key: z.string(),
});
export type TranscribePayload = z.infer<typeof TranscribePayloadSchema>;

export const StructurePayloadSchema = z.object({
  jobId: z.string().uuid(),
  rawText: z.string().min(10),
});
export type StructurePayload = z.infer<typeof StructurePayloadSchema>;

export const RenderPayloadSchema = z.object({
  jobId: z.string().uuid(),
});
export type RenderPayload = z.infer<typeof RenderPayloadSchema>;

// Slide Data (used by render pipeline)
export interface SlideData {
  type: 'hook' | 'value' | 'cta';
  index: number;
  heading: string;
  body?: string;
  bulletPoints?: string[];
  subtitle?: string;
  ctaUrl?: string;
  design?: SlideDesign;
}

export function buildSlides(content: StructuredContent): SlideData[] {
  const slides: SlideData[] = [];

  slides.push({
    type: 'hook',
    index: 0,
    heading: content.hook.title,
    subtitle: content.hook.subtitle,
  });

  content.valuePoints.forEach((vp, i) => {
    slides.push({
      type: 'value',
      index: i + 1,
      heading: vp.heading,
      body: vp.body,
      bulletPoints: vp.bulletPoints,
    });
  });

  slides.push({
    type: 'cta',
    index: content.valuePoints.length + 1,
    heading: content.callToAction.message,
    ctaUrl: content.callToAction.url,
  });

  return slides;
}

// Build slides with design metadata
export function buildSlidesWithDesign(
  content: StructuredContent,
  design: DesignOutput
): SlideData[] {
  const slides = buildSlides(content);

  return slides.map((slide, i) => ({
    ...slide,
    design: design.slides[i],
  }));
}
