const { resolve } = require('path');
const LOG_DIR = resolve(__dirname, 'logs');

const localEnv = {
  DATABASE_URL: 'postgresql://loopreel:loopreel@localhost:5432/loopreel',
  REDIS_URL: 'redis://localhost:6379',
  LLM_PROVIDER: 'mock',
  LOG_LEVEL: 'info',
};

module.exports = {
  apps: [
    {
      name: 'loop-engine',
      script: 'npx',
      args: 'vite --host --port 5173',
      cwd: resolve(__dirname, 'packages/loop'),
      watch: false,
      autorestart: true,
      max_restarts: 10,
      error_file: resolve(LOG_DIR, 'loop-engine-error.log'),
      out_file: resolve(LOG_DIR, 'loop-engine-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
    {
      name: 'api',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/api'),
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'api-error.log'),
      out_file: resolve(LOG_DIR, 'api-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
    {
      name: 'worker-ingest',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-ingest'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-ingest-error.log'),
      out_file: resolve(LOG_DIR, 'worker-ingest-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
    {
      name: 'worker-transcribe',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-transcribe'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-transcribe-error.log'),
      out_file: resolve(LOG_DIR, 'worker-transcribe-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
    {
      name: 'worker-structure',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-structure'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-structure-error.log'),
      out_file: resolve(LOG_DIR, 'worker-structure-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
    {
      name: 'worker-render',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-render'),
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-render-error.log'),
      out_file: resolve(LOG_DIR, 'worker-render-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development', ...localEnv },
    },
  ],
};
