const { resolve } = require('path');
const LOG_DIR = resolve(__dirname, 'logs');

module.exports = {
  apps: [
    {
      name: 'api',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/api'),
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'api-error.log'),
      out_file: resolve(LOG_DIR, 'api-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'web',
      script: 'pnpm',
      args: '--filter @loopreel/web dev',
      cwd: resolve(__dirname),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'web-error.log'),
      out_file: resolve(LOG_DIR, 'web-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'worker-relay',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-relay'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-relay-error.log'),
      out_file: resolve(LOG_DIR, 'worker-relay-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'worker-ingest',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-ingest'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-ingest-error.log'),
      out_file: resolve(LOG_DIR, 'worker-ingest-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'worker-transcribe',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-transcribe'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-transcribe-error.log'),
      out_file: resolve(LOG_DIR, 'worker-transcribe-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'worker-structure',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-structure'),
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-structure-error.log'),
      out_file: resolve(LOG_DIR, 'worker-structure-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
    {
      name: 'worker-render',
      script: 'node',
      args: '--import tsx src/bootstrap.ts',
      cwd: resolve(__dirname, 'apps/worker-render'),
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
      error_file: resolve(LOG_DIR, 'worker-render-error.log'),
      out_file: resolve(LOG_DIR, 'worker-render-out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      env: { NODE_ENV: 'development' },
    },
  ],
};
