import type { TheAcademicContract } from './schema';

const slides: TheAcademicContract = {
  slides: [
    {
      id: 'ta-cover-1', type: 'cover',
      tag: 'ABSTRACT',
      headline: 'The Organizational Friction Matrix.',
      subheadline: 'This paper examines the counter-intuitive paradigm wherein intentionally introducing cognitive and procedural friction within client acquisition funnels yields a statistically significant expansion in net margins and lifetime value.',
      authorName: 'Dr. Arthur Vance',
      authorRole: 'Department of Behavioral Economics',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 01',
    },
    {
      id: 'ta-seq-1', type: 'sequence',
      tag: 'SUMMARY',
      headline: 'Executive Summary',
      items: [
        { num: '1.0', title: 'The Scarcity Premium', desc: 'Restricting total active client volume strictly to 12 accounts generated a 3.5x multiplier on perceived baseline value.' },
        { num: '2.0', title: 'Automated Disqualification', desc: 'Requiring extensive preliminary documentation reduced sales call volume by 80% while increasing close rates to 92%.' },
        { num: '3.0', title: 'Margin Expansion', desc: 'The transition from deliverables-based billing to advisory retainers expanded net profit margins from 18% to 74%.' },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 02',
    },
    {
      id: 'ta-img-1', type: 'image-split',
      tag: 'OBSERVATION',
      headline: 'Structural Integrity',
      bodyText: 'In observed cohorts, agencies lacking rigid boundary constraints experienced rapid scope erosion. The architecture of the engagement must be defined mathematically before any tactical execution begins.',
      imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?q=80&w=1080&auto=format&fit=crop',
      credit: 'FIG. 01 — STRUCTURE',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 03',
    },
    {
      id: 'ta-telem-1', type: 'telemetry',
      tag: 'EMPIRICAL DATA',
      headline: 'Empirical Findings',
      stats: [
        { value: '42', unit: '%', label: 'Increase in Lifetime Value', color: 'crimson' },
        { value: '3.5', unit: 'x', label: 'Premium Price Multiplier', color: 'ink' },
        { value: '-80', unit: '%', label: 'Reduction in Sales Calls', color: 'graphite' },
        { value: '92', unit: '%', label: 'Retention Rate (Y1)', color: 'crimson' },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 04',
    },
    {
      id: 'ta-interview-1', type: 'interview',
      tag: 'PEER REVIEW',
      headline: 'Analytical Inquiry',
      question: 'Does implementing extreme friction alienate the broader market and restrict aggregate revenue growth?',
      answer: 'Yes, and that is precisely the mathematical objective. Broad market alienation filters out low-margin, high-maintenance accounts. By restricting volume, the firm reallocates resources to high-net-worth cohorts, trading top-line vanity metrics for exponential net profit expansion.',
      respondentName: 'Review Board Commentary',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 05',
    },
    {
      id: 'ta-quad-1', type: 'quadrant',
      tag: 'FRAMEWORK',
      headline: 'The Value Matrix',
      topLeft: { title: 'The Grinder', desc: 'Competing purely on volume and price. A stressful race to the bottom.' },
      topRight: { title: 'The Authority', desc: 'Premium positioning. High friction. Asymmetric leverage and massive ROI.', highlighted: true },
      bottomLeft: { title: 'The Martyr', desc: 'Incredible talent, terrible boundaries. Over-delivers until burnout.' },
      bottomRight: { title: 'The Extortionist', desc: 'Legacy agencies charging for bloated overhead with no measurable ROI.' },
      topLabel: 'High Friction', bottomLabel: 'Low Friction',
      leftLabel: 'Commodity', rightLabel: 'Specialized',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 06',
    },
    {
      id: 'ta-cs-1', type: 'case-study',
      tag: 'LONGITUDINAL',
      headline: 'Clinical Observation',
      stages: [
        { label: 'Hypothesis', title: 'Bloated Infrastructure', desc: 'Firm was stalled at $50k/mo with 30 active clients. Team reported severe burnout and churn rate reached 15%.' },
        { label: 'Intervention', title: 'The Flattening', desc: 'Eliminated bottom 20% of clients. Quadrupled base price. Instituted strict application-only onboarding.' },
        { label: 'Outcome', title: 'Margin Expansion', desc: 'Firm scaled to $250k/mo with only 12 active clients. Net profit margin expanded from 18% to 68%.', highlighted: true },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 07',
    },
    {
      id: 'ta-myth-1', type: 'myth-fact',
      tag: 'HYPOTHESIS',
      headline: 'Theoretical Correction',
      myth: 'Agencies must inevitably choose between compounding revenue growth and sustainable profitability/margins.',
      fact: 'True operational leverage allows for compounding growth while simultaneously expanding margins. Constraint is a catalyst, not a limiter.',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 08',
    },
    {
      id: 'ta-res-1', type: 'resource-grid',
      tag: 'LIT REVIEW',
      headline: 'Literature Review',
      items: [
        { title: 'Bloomberg Terminal', desc: 'The undisputed heavyweight for real-time macroeconomic data, news, and complex financial instruments.', color: 'crimson' },
        { title: 'Capital IQ', desc: 'Essential for deep fundamental analysis, M&A tracking, and untangling complex global corporate structures.', color: 'ink' },
        { title: 'The Economist', desc: 'Weekly synthesis of global affairs providing the critical qualitative context required beyond the raw data.', color: 'ink' },
        { title: 'Stratfor', desc: 'Geopolitical intelligence platform used by executives to anticipate regulatory and major supply chain shifts.', color: 'ink' },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 09',
    },
    {
      id: 'ta-tl-1', type: 'timeline',
      tag: 'METHODOLOGY',
      headline: 'Research Methodology',
      events: [
        { date: 'PHASE I', title: 'Data Collection', desc: 'Quantitative metrics aggregated from 400 mid-market agencies over a 36-month longitudinal study.' },
        { date: 'PHASE II', title: 'Variable Isolation', desc: 'Controlled for macroeconomic shifts, isolating onboarding friction as the primary independent variable.' },
        { date: 'PHASE III', title: 'Regression Analysis', desc: 'Proving statistically significant correlation (p < 0.01) between restricted access and margin expansion.', highlight: true },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 10',
    },
    {
      id: 'ta-quote-1', type: 'quote',
      tag: 'CITATION',
      quote: 'In an ecosystem defined by infinite commodity supply, the only remaining vector for premium pricing is the artificial curation of access.',
      author: 'Prof. E. Rostova',
      role: 'Journal of Behavioral Economics, 2025',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 11',
    },
    {
      id: 'ta-cta-1', type: 'cta',
      tag: 'ACQUISITION',
      headline: 'Review the Full Manuscript.',
      subtext: 'Access the complete dataset, regression models, and implementation protocols.',
      actionLabel: 'Download PDF [2.4MB]',
      socialHandle: 'Available via University Portal',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 12',
    },
    {
      id: 'ta-hero-1', type: 'hero-metric',
      tag: 'SIGNIFICANCE',
      value: '90', unit: '%',
      headline: 'Information Retention Decay',
      bodyText: 'Human subjects demonstrated a near-total inability to retain strategic data when presented without clear visual hierarchy and negative space.',
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 13',
    },
    {
      id: 'ta-method-1', type: 'methodology',
      tag: 'DESIGN',
      headline: 'Experimental Design',
      steps: [
        { num: 'A', title: 'Isolation of Variables', desc: 'Remove the subject from all contextual noise and decorative elements to establish a baseline.' },
        { num: 'B', title: 'Proportional Scaling', desc: 'Scale the essential elements to absolute maximum visibility. Create psychological tension.' },
        { num: 'C', title: 'Execution Protocol', desc: 'Publish with uncompromising discipline. Reject qualitative requests for visual pop.', highlighted: true },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 14',
    },
    {
      id: 'ta-juxta-1', type: 'juxtaposition',
      tag: 'PARADIGM',
      headline: 'Comparative Paradigms',
      donts: ['Volume-based client acquisition.', 'Hourly billing structures.', 'Automated, frictionless onboarding.'],
      dos: ['Strictly capped roster limits.', 'Value-based retainer pricing.', 'High-friction application gateways.'],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 15',
    },
    {
      id: 'ta-check-1', type: 'checklist',
      tag: 'AUDIT',
      headline: 'Implementation Audit',
      items: [
        { text: 'Has all commoditized service execution been eliminated from the core offer?' },
        { text: 'Is there a mandatory financial or cognitive hurdle before a sales interaction?' },
        { text: 'Is the pricing architecture disconnected entirely from time and materials?', checked: true },
        { text: 'Are client capacity limits publicly visible and mathematically enforced?' },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 16',
    },
    {
      id: 'ta-break-1', type: 'breakdown',
      tag: 'ARCHITECTURE',
      headline: 'System Architecture',
      centerLabel: 'Optimal Margin',
      items: [
        { num: '01', title: 'Scarcity Engine', desc: 'Hard-coded limits on concurrent engagements to drive demand.' },
        { num: '02', title: 'Friction Gate', desc: 'Application models designed to repel low-intent prospects.' },
        { num: '03', title: 'Asymmetric Value', desc: 'Delivering strategic insights rather than commoditized labor.' },
        { num: '04', title: 'Price Inelasticity', desc: 'Decoupling fees from hours to capture the true economic surplus.' },
      ],
      footerLeft: 'DOI: 10.1016/J.BUSRES.2026', footerRight: 'PAGE 17',
    },
  ],
};

export default slides;
