import type { PaperOfRecordContract } from './schema';

const slides: PaperOfRecordContract = {
  slides: [
    {
      id: 'por-cover-1', type: 'cover',
      tag: 'INVESTIGATION',
      headline: 'The Silent Collapse of the Global Attention Economy.',
      subheadline: 'How algorithms engineered to maximize engagement have inadvertently destroyed the human capacity for deep work.',
      authorName: 'Sarah K. Kingsley',
      authorRole: 'Reporting from San Francisco',
      footerLeft: 'TECHNOLOGY', footerRight: 'PAGE 01',
    },
    {
      id: 'por-quote-1', type: 'quote',
      tag: 'OPINION',
      quote: "We didn't build a product. We built a slot machine that operates on human psychological vulnerabilities.",
      author: 'Dr. Arthur Vance',
      role: 'Former Director of Behavioral Engineering',
      footerLeft: 'THE DAILY', footerRight: 'PAGE 02',
    },
    {
      id: 'por-def-1', type: 'definition',
      tag: 'GLOSSARY',
      term: 'Algorithmic Decay.',
      phonetic: '[al-gə-ˈriTH-mik di-ˈkā]',
      definition: 'The gradual degradation of platform utility caused by optimization models prioritizing short-term outrage over long-term informational value.',
      example: 'Note: First identified by researchers at MIT in late 2023.',
      footerLeft: 'CONTEXT', footerRight: 'PAGE 03',
    },
    {
      id: 'por-seq-1', type: 'sequence',
      tag: 'THE BRIEFING',
      headline: 'What You Need to Know',
      items: [
        { num: '1.', title: 'The Dopamine Deficit', desc: 'Users are experiencing measurable chemical exhaustion after 45 minutes of continuous short-form video consumption.' },
        { num: '2.', title: 'The Pivot to Private', desc: 'High-net-worth individuals are increasingly abandoning public social squares in favor of encrypted, invite-only micro-communities.' },
        { num: '3.', title: 'Regulatory Looming', desc: 'The EU is drafting legislation to classify algorithmic feeds as "addictive substances" requiring strict age gating.' },
      ],
      footerLeft: 'THE BRIEFING', footerRight: 'PAGE 04',
    },
    {
      id: 'por-dich-1', type: 'dichotomy',
      tag: 'PERSPECTIVES',
      headline: 'The Great Divide',
      left: { title: '"Connecting the World"', desc: 'Executives argue that their models merely reflect human nature, serving people exactly what they engage with most. They point to billions connected globally as proof of unmitigated success.' },
      right: { title: '"Exploiting the Mind"', desc: 'Academics counter that the systems bypass rational thought, targeting the brain stem. It is not connection, they argue, but a sophisticated extraction of human time and sanity for ad revenue.' },
      leftLabel: 'THE PLATFORMS',
      rightLabel: 'THE RESEARCHERS',
      footerLeft: 'ANALYSIS', footerRight: 'PAGE 05',
    },
    {
      id: 'por-telem-1', type: 'telemetry',
      tag: 'STATISTICS',
      headline: 'By the Numbers',
      stats: [
        { value: '4.2', unit: 'B', label: 'Hours lost daily to algorithmic scrolling by the average adult in the US.' },
        { value: '78', unit: '%', label: 'Increase in teen anxiety disorders directly linked to platform usage since 2012.' },
        { value: '$11', unit: 'T', label: 'Estimated global economic impact of lost productivity annually.' },
        { value: '12', unit: 'sec', label: 'The current average attention span of Gen-Z consumers, down from 30 seconds.' },
      ],
      footerLeft: 'DATA SET', footerRight: 'PAGE 06',
    },
    {
      id: 'por-tl-1', type: 'timeline',
      tag: 'TIMELINE',
      headline: 'How We Got Here',
      events: [
        { date: '2009', title: 'The "Like" Button', desc: 'Introduced as a tool for positivity, it creates the first quantifiable metric of social approval, gamifying human interaction.' },
        { date: '2016', title: 'The Algorithmic Feed', desc: 'Chronological feeds are abandoned. Machine learning dictates what users see, optimizing purely for time-on-screen.' },
        { date: '2026', title: 'The Saturation Point', desc: 'AI-generated content floods the feeds, rendering the platforms unusable for organic human connection.', highlight: true },
      ],
      footerLeft: 'CHRONOLOGY', footerRight: 'PAGE 07',
    },
    {
      id: 'por-img-1', type: 'image-split',
      tag: 'PHOTO ESSAY',
      headline: 'The Hardware Inside',
      bodyText: 'Server farms in Northern Virginia process petabytes of behavioral data daily. The physical infrastructure required to sustain the attention economy consumes more energy than several small nations combined.',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1080&auto=format&fit=crop',
      credit: 'Photograph by Unsplash / NYT',
      footerLeft: 'PHOTOJOURNALISM', footerRight: 'PAGE 08',
    },
    {
      id: 'por-tbl-1', type: 'table',
      tag: 'DATA DESK',
      headline: 'Platform Toxicity Index',
      headers: ['Platform', 'Daily Min', 'Stress Spike', 'Verdict'],
      rows: [
        ['VideoFeed', '112m', '+45%', 'Severe'],
        ['TextSquare', '45m', '+68%', 'Critical'],
        ['PhotoGrid', '58m', '+22%', 'Moderate'],
        ['ReadingApp', '25m', '-12%', 'Healthy'],
      ],
      highlightRow: 3,
      footerLeft: 'ANALYSIS', footerRight: 'PAGE 09',
    },
    {
      id: 'por-analysis-1', type: 'analysis',
      tag: 'ANALYSIS',
      headline: 'Analysis: The Opt-Out',
      bodyText: 'There is a growing movement among the technological elite to entirely disconnect their children from the very systems they built. In Silicon Valley, nanny contracts now routinely include strict "no-screen" clauses. This creates a fascinating paradox: the architects of the attention economy treat their own product like a hazardous material. As this awareness trickles down to the middle class, we are seeing the first widespread adoption of "dumb phones" and timed router lockouts. The future of luxury may no longer be defined by what you have access to, but by what you have the privilege to ignore.',
      footerLeft: 'DEEP READ', footerRight: 'PAGE 10',
    },
    {
      id: 'por-profile-1', type: 'profile',
      tag: 'Case Study',
      headline: 'The Digital Hermit',
      portraitUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop',
      personName: 'Marcus Vance, 42',
      personRole: 'Former Tech Executive',
      quote: "I spent ten years optimizing notifications to ensure users checked their phones 150 times a day. When I realized my own daughter couldn't read a book for ten minutes without twitching, I resigned. Now I consult on digital detox architecture.",
      footerLeft: 'PROFILE', footerRight: 'PAGE 11',
    },
    {
      id: 'por-cta-1', type: 'cta',
      tag: 'THE DAILY',
      headline: 'Understand the forces shaping our world.',
      subtext: 'Read the full investigative report.',
      actionLabel: 'Subscribe for Access',
      socialHandle: 'Link in Bio',
      footerLeft: 'SUBSCRIPTION', footerRight: 'PAGE 12',
    },
  ],
};

export default slides;
